trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  parallel: 1

steps:
- script: |
    echo "Listing all files in $(Build.SourcesDirectory)"
    ls -al $(Build.SourcesDirectory)
    echo "Checking for Dockerfile"
    if [ -f $(Build.SourcesDirectory)/Dockerfile ]; then
      echo "Dockerfile found."
    else
      echo "Dockerfile not found."
      exit 1
    fi
  displayName: 'List files and check for Dockerfile'
- task: Docker@2
  displayName: 'Build and Push Docker image'
  inputs:
    containerRegistry: 'Docker Hub' 
    command: 'buildAndPush' 
    repository: 'walaab/aicorefinalproject' 
    dockerfile: '**/Dockerfile' 
    tags: 'latest'
- task: Kubernetes@1
  displayName: 'Deploy to AKS'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'aicore-AzureCloud'
    azureResourceGroup: 'networking-resource-group'
    kubernetesCluster: 'terraform-aks-cluster'
    command: 'apply'
    arguments: '-f $(System.DefaultWorkingDirectory)/aks-terraform/application-manifest.yaml'
