trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  parallel: 1

steps:
- task: Kubernetes@1
  displayName: 'Deploy to AKS'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'aicore-AzureCloud'
    azureResourceGroup: 'networking-resource-group'
    kubernetesCluster: 'terraform-aks-cluster'
    command: 'apply'
    arguments: '-f $(System.DefaultWorkingDirectory)/aks-terraform/application-manifest.yaml'
