trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker image'
  inputs:
    containerRegistry: 'DockerHubConnection1' 
    command: 'buildAndPush' 
    repository: 'walaab/aicore_finalproject' 
    dockerfile: '**/Dockerfile' 
    tags: |
      latest
      $(Build.BuildId)
  
  - task: Kubernetes@1
    displayName: 'Deploy to AKS'
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: 'aicore-AzureCloud' 
      azureResourceGroup: 'networking-resource-group' 
      kubernetesCluster: 'terraform-aks-cluster' # Use the cluster name from your Terraform configuration
      command: 'apply'
      arguments: '-f $(System.DefaultWorkingDirectory)/aks-terraform/application-manifest.yaml' # Path to your manifest file
