trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker image'
  inputs:
    containerRegistry: 'DockerHubConnection'  # Use the service connection name you created earlier
    command: 'buildAndPush' 
    repository: 'walaab/aicore_finalproject' 
    dockerfile: '**/Dockerfile' 
    tags: |
      latest
      $(Build.BuildId)
